package Vistas;

import Modelo.Conexion;
import Modelo.MetodosSQL;
import Modelo.Pedido;
import Modelo.Producto;
import Modelo.Proveedor;
import Modelo.Sucursal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class VistaPedidosRealizados extends javax.swing.JFrame {

    public VistaPedidosRealizados() {
        initComponents();
        this.setLocationRelativeTo(this);
        añadirPedidos();
        /*
        DefaultTableCellRenderer alineacion = new DefaultTableCellRenderer();
        alineacion.setHorizontalAlignment(SwingConstants.CENTER);        
        for(int i = 0; i < tablaPedidos.getColumnCount(); i++){
            tablaPedidos.getColumnModel().getColumn(i).setCellRenderer(alineacion);            
        }
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        fondoEncabezado = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fondoTitulo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        cancelarPedidoBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPedidos = new javax.swing.JTable();
        regresarBtn = new javax.swing.JButton();
        editarPedidoBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setPreferredSize(new java.awt.Dimension(1366, 768));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoEncabezado.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout fondoEncabezadoLayout = new javax.swing.GroupLayout(fondoEncabezado);
        fondoEncabezado.setLayout(fondoEncabezadoLayout);
        fondoEncabezadoLayout.setHorizontalGroup(
            fondoEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoEncabezadoLayout.setVerticalGroup(
            fondoEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        fondo.add(fondoEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, -1));

        fondoTitulo.setBackground(new java.awt.Color(255, 0, 0));

        titulo.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("PEDIDOS REALIZADOS");

        javax.swing.GroupLayout fondoTituloLayout = new javax.swing.GroupLayout(fondoTitulo);
        fondoTitulo.setLayout(fondoTituloLayout);
        fondoTituloLayout.setHorizontalGroup(
            fondoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoTituloLayout.createSequentialGroup()
                .addContainerGap(540, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(532, 532, 532))
        );
        fondoTituloLayout.setVerticalGroup(
            fondoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        fondo.add(fondoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1440, -1));

        cancelarPedidoBtn.setBackground(new java.awt.Color(255, 0, 0));
        cancelarPedidoBtn.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        cancelarPedidoBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelarPedidoBtn.setText("CANCELAR PEDIDO");
        cancelarPedidoBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelarPedidoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarPedidoBtnActionPerformed(evt);
            }
        });
        fondo.add(cancelarPedidoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 740, -1, 48));

        tablaPedidos.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        tablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaPedidos);

        fondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 1380, 460));

        regresarBtn.setBackground(new java.awt.Color(255, 0, 0));
        regresarBtn.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        regresarBtn.setForeground(new java.awt.Color(255, 255, 255));
        regresarBtn.setText("REGRESAR");
        regresarBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });
        fondo.add(regresarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 740, -1, 48));

        editarPedidoBtn.setBackground(new java.awt.Color(255, 0, 0));
        editarPedidoBtn.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        editarPedidoBtn.setForeground(new java.awt.Color(255, 255, 255));
        editarPedidoBtn.setText("EDITAR PEDIDO");
        editarPedidoBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editarPedidoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarPedidoBtnActionPerformed(evt);
            }
        });
        fondo.add(editarPedidoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 740, -1, 48));
        fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N
        fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarPedidoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarPedidoBtnActionPerformed
        MetodosSQL metodos = new MetodosSQL();
        Proveedor proveedor = new Proveedor();
        Sucursal sucursal = new Sucursal();
        Producto producto = new Producto();
        Pedido pedido = new Pedido();
        
        int fila = tablaPedidos.getSelectedRow();
        try{            
            if(fila == -1){
                JOptionPane.showMessageDialog(this, "No se ha seleccionado un pedido", "Pedido no seleccionado", JOptionPane.WARNING_MESSAGE);             
            }else{
                
                String idPedido = tablaPedidos.getValueAt(fila, 0).toString();                
                
                int pedidoInt = Integer.parseInt(idPedido);
                pedido.setId_pedido(pedidoInt);
            
                if(metodos.cancelarPedido(pedido)){                    
                    añadirPedidos();
                    JOptionPane.showMessageDialog(this, "Pedido cancelado correctamente", "Pedido cancelado", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(this, "No se ha podido cancelar el pedido", "Pedido no cancelado", JOptionPane.ERROR_MESSAGE);
                }
            }            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "No se ha seleccionado un pedido", "Pedido no seleccionado", JOptionPane.WARNING_MESSAGE);
        }               
    }//GEN-LAST:event_cancelarPedidoBtnActionPerformed

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        VistaMenu menu = new VistaMenu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresarBtnActionPerformed

    private void editarPedidoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarPedidoBtnActionPerformed
        MetodosSQL metodos = new MetodosSQL();
        Proveedor proveedor = new Proveedor();
        Sucursal sucursal = new Sucursal();
        Producto producto = new Producto();
        Pedido pedido = new Pedido();
        
        int fila = tablaPedidos.getSelectedRow();
        try{            
            if(fila == -1){
                JOptionPane.showMessageDialog(this, "No se ha seleccionado un pedido", "Pedido no seleccionado", JOptionPane.WARNING_MESSAGE);             
            }else{
                
                String idPedido = tablaPedidos.getValueAt(fila, 0).toString();
                String idProducto = tablaPedidos.getValueAt(fila, 1).toString();
                String nombreProducto = tablaPedidos.getValueAt(fila, 2).toString();
                String idProveedor = tablaPedidos.getValueAt(fila, 3).toString();
                String nombreProveedor = tablaPedidos.getValueAt(fila, 4).toString();
                String nombreSucursal = tablaPedidos.getValueAt(fila, 5).toString();               
                String tipoProducto = tablaPedidos.getValueAt(fila, 6).toString();   
                String cantidad = tablaPedidos.getValueAt(fila, 7).toString();                   
                
                int pedidoInt = Integer.parseInt(idPedido);
                pedido.setId_pedido(pedidoInt);
                int productoInt = Integer.parseInt(idProducto);
                pedido.setCodigo_producto(productoInt);
                int proveedorInt = Integer.parseInt(idProveedor);
                pedido.setCodigo_proveedor(proveedorInt);
                pedido.setTipo_producto(tipoProducto);
                int cantidadInt = Integer.parseInt(cantidad);
                pedido.setCantidad(cantidadInt);     
                producto.setNombre(nombreProducto);
                proveedor.setNombre(nombreProveedor);
                sucursal.setNombre(nombreSucursal);
                
                VistaModificarPedido modificarPedido = new VistaModificarPedido(proveedor, sucursal, producto, pedido);
                modificarPedido.setVisible(true);
                this.setVisible(false);
            }            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "No se ha seleccionado un pedido", "Pedido no seleccionado", JOptionPane.WARNING_MESSAGE);
        } 
    }//GEN-LAST:event_editarPedidoBtnActionPerformed

    public void añadirPedidos() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID pedido");
        modelo.addColumn("ID producto");
        modelo.addColumn("Nombre producto");
        modelo.addColumn("ID proveedor");
        modelo.addColumn("Nombre proveedor");
        modelo.addColumn("Sucursal");
        modelo.addColumn("Tipo de producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Estado");

        tablaPedidos.setModel(modelo);

        Conexion conn = new Conexion();
        Connection reg = conn.conectar();
        Connection con = reg;

        PreparedStatement ps = null;
        ResultSet rs = null;

        String[] datos = new String[9];

        String sql = "SELECT * FROM pedidos INNER JOIN producto ON pedidos.producto = producto.codigo_producto INNER JOIN proveedor ON pedidos.proveedor = proveedor.codigo_proveedor";

        try {
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(9);
                datos[3] = rs.getString(3);
                datos[4] = rs.getString(11);
                datos[5] = rs.getString(4);
                datos[6] = rs.getString(5);
                datos[7] = rs.getString(6);
                datos[8] = rs.getString(7);
                modelo.addRow(datos);
            }
            tablaPedidos.setModel(modelo);

        } catch (Exception e) {
            System.out.println("Error en la consulta: " + e);

        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPedidosRealizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPedidosRealizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPedidosRealizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPedidosRealizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPedidosRealizados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarPedidoBtn;
    private javax.swing.JButton editarPedidoBtn;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel fondoEncabezado;
    private javax.swing.JPanel fondoTitulo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton regresarBtn;
    private javax.swing.JTable tablaPedidos;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
