package Vistas;

import Modelo.MetodosSQL;
import Modelo.Personal;
import javax.swing.JOptionPane;

public class VistaAltaPersonal extends javax.swing.JFrame {

    public VistaAltaPersonal() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        fondoEncabezado = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fondoTitulo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        contraseñaLabel = new javax.swing.JLabel();
        usuarioLabel = new javax.swing.JLabel();
        darAltaBtn = new javax.swing.JButton();
        regresarBtn = new javax.swing.JButton();
        contraseñaLabel2 = new javax.swing.JLabel();
        contraseñaLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        curpTxt = new javax.swing.JTextField();
        nombreTxt = new javax.swing.JTextField();
        apellidoPaternoTxt = new javax.swing.JTextField();
        apellidoMaternoTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setPreferredSize(new java.awt.Dimension(1366, 768));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoEncabezado.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout fondoEncabezadoLayout = new javax.swing.GroupLayout(fondoEncabezado);
        fondoEncabezado.setLayout(fondoEncabezadoLayout);
        fondoEncabezadoLayout.setHorizontalGroup(
            fondoEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoEncabezadoLayout.setVerticalGroup(
            fondoEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fondo.add(fondoEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, -1));

        fondoTitulo.setBackground(new java.awt.Color(255, 51, 51));

        titulo.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("ALTA DE PERSONAL");

        javax.swing.GroupLayout fondoTituloLayout = new javax.swing.GroupLayout(fondoTitulo);
        fondoTitulo.setLayout(fondoTituloLayout);
        fondoTituloLayout.setHorizontalGroup(
            fondoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoTituloLayout.createSequentialGroup()
                .addContainerGap(569, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(449, 449, 449))
        );
        fondoTituloLayout.setVerticalGroup(
            fondoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
        );

        fondo.add(fondoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1440, 60));

        contraseñaLabel.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        contraseñaLabel.setText("APELLIDO PATERNO:");
        fondo.add(contraseñaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, -1, -1));

        usuarioLabel.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        usuarioLabel.setText("NOMBRE:");
        fondo.add(usuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, -1, -1));

        darAltaBtn.setBackground(new java.awt.Color(255, 0, 0));
        darAltaBtn.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        darAltaBtn.setForeground(new java.awt.Color(255, 255, 255));
        darAltaBtn.setText("DAR DE ALTA");
        darAltaBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        darAltaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darAltaBtnActionPerformed(evt);
            }
        });
        fondo.add(darAltaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 770, 230, 48));

        regresarBtn.setBackground(new java.awt.Color(255, 0, 0));
        regresarBtn.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        regresarBtn.setForeground(new java.awt.Color(255, 255, 255));
        regresarBtn.setText("REGRESAR");
        regresarBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });
        fondo.add(regresarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 770, -1, 48));

        contraseñaLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        contraseñaLabel2.setText("APELLIDO MATERNO:");
        fondo.add(contraseñaLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, -1, -1));

        contraseñaLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        contraseñaLabel3.setText("CURP:");
        fondo.add(contraseñaLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 600, -1, 50));
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        curpTxt.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        fondo.add(curpTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 640, 417, 54));

        nombreTxt.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        fondo.add(nombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 417, 54));

        apellidoPaternoTxt.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        fondo.add(apellidoPaternoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 417, 54));

        apellidoMaternoTxt.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        fondo.add(apellidoMaternoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, 417, 54));
        fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, -1));
        fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 16, -1, 110));
        fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N
        fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inicia_sesion.png"))); // NOI18N
        fondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void darAltaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darAltaBtnActionPerformed
        Personal personal = new Personal();
        MetodosSQL metodos = new MetodosSQL();
        
        if(curpTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar su CURP", "CURP vacía", JOptionPane.ERROR_MESSAGE);            
        }else if(nombreTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar su nombre", "Nombre vacío", JOptionPane.ERROR_MESSAGE);            
        }else if(apellidoPaternoTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar su apellido materno", "Apellido paterno vacío", JOptionPane.ERROR_MESSAGE);            
        }else if(apellidoMaternoTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar su apellido materno", "Apellido materno vacío", JOptionPane.ERROR_MESSAGE);            
        }else{
            personal.setCurp(curpTxt.getText());
            personal.setNombre(nombreTxt.getText());
            personal.setApellidoPaterno(apellidoPaternoTxt.getText());
            personal.setApellidoMaterno(apellidoMaternoTxt.getText());
            if(metodos.validarCurp(personal)){
                JOptionPane.showMessageDialog(this, "La persona ya está dada de alta", "CURP dada de alta", JOptionPane.ERROR_MESSAGE);
            }else{
                if(metodos.altaPersonal(personal)){
                    VistaMenu menu = new VistaMenu();
                    menu.setVisible(true);
                    this.setVisible(false);
                } 
            }               
        }                    
    }//GEN-LAST:event_darAltaBtnActionPerformed

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        VistaMenu menu = new VistaMenu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAltaPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAltaPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAltaPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAltaPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAltaPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoMaternoTxt;
    private javax.swing.JTextField apellidoPaternoTxt;
    private javax.swing.JLabel contraseñaLabel;
    private javax.swing.JLabel contraseñaLabel2;
    private javax.swing.JLabel contraseñaLabel3;
    private javax.swing.JTextField curpTxt;
    private javax.swing.JButton darAltaBtn;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel fondoEncabezado;
    private javax.swing.JPanel fondoTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JButton regresarBtn;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel usuarioLabel;
    // End of variables declaration//GEN-END:variables
}
