package Vistas;

import Modelo.Acceso;
import Modelo.MetodosSQL;
import javax.swing.JOptionPane;

public class VistaIniciarSesion extends javax.swing.JFrame {
    
    public VistaIniciarSesion() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        fondoEncabezado = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fondoTitulo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        contraseñaLabel = new javax.swing.JLabel();
        usuarioLabel = new javax.swing.JLabel();
        iniciarSesionBtn = new javax.swing.JButton();
        salirBtn = new javax.swing.JButton();
        curpTxt = new javax.swing.JTextField();
        contraseñaTxt = new javax.swing.JPasswordField();
        registrarseBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setPreferredSize(new java.awt.Dimension(1366, 768));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoEncabezado.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout fondoEncabezadoLayout = new javax.swing.GroupLayout(fondoEncabezado);
        fondoEncabezado.setLayout(fondoEncabezadoLayout);
        fondoEncabezadoLayout.setHorizontalGroup(
            fondoEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoEncabezadoLayout.setVerticalGroup(
            fondoEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fondo.add(fondoEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, -1));

        fondoTitulo.setBackground(new java.awt.Color(255, 0, 0));

        titulo.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("INICIAR SESIÓN");

        javax.swing.GroupLayout fondoTituloLayout = new javax.swing.GroupLayout(fondoTitulo);
        fondoTitulo.setLayout(fondoTituloLayout);
        fondoTituloLayout.setHorizontalGroup(
            fondoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoTituloLayout.createSequentialGroup()
                .addContainerGap(603, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(580, 580, 580))
        );
        fondoTituloLayout.setVerticalGroup(
            fondoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo))
        );

        fondo.add(fondoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1440, -1));

        contraseñaLabel.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        contraseñaLabel.setText("CONTRASEÑA:");
        fondo.add(contraseñaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, -1, 90));

        usuarioLabel.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        usuarioLabel.setText("CURP:");
        fondo.add(usuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, -1, -1));

        iniciarSesionBtn.setBackground(new java.awt.Color(255, 0, 0));
        iniciarSesionBtn.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        iniciarSesionBtn.setForeground(new java.awt.Color(255, 255, 255));
        iniciarSesionBtn.setText("INICIAR SESIÓN");
        iniciarSesionBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iniciarSesionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionBtnActionPerformed(evt);
            }
        });
        fondo.add(iniciarSesionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 730, 230, 48));

        salirBtn.setBackground(new java.awt.Color(255, 0, 0));
        salirBtn.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        salirBtn.setForeground(new java.awt.Color(255, 255, 255));
        salirBtn.setText("SALIR");
        salirBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });
        fondo.add(salirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 740, -1, 48));

        curpTxt.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        fondo.add(curpTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 417, 54));

        contraseñaTxt.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        fondo.add(contraseñaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, 420, 50));

        registrarseBtn.setBackground(new java.awt.Color(255, 0, 0));
        registrarseBtn.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        registrarseBtn.setForeground(new java.awt.Color(255, 255, 255));
        registrarseBtn.setText("REGISTRARSE");
        registrarseBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        registrarseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseBtnActionPerformed(evt);
            }
        });
        fondo.add(registrarseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 740, -1, 48));
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));
        fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iniciar_sesion.png"))); // NOI18N
        fondo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N
        fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarSesionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionBtnActionPerformed
        Acceso acceso = new Acceso();
        MetodosSQL metodos = new MetodosSQL();
        
        char[] contraseñaArray = contraseñaTxt.getPassword();
        String contraseña = new String(contraseñaArray);

        
        if(curpTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar su CURP", "CURP vacía", JOptionPane.ERROR_MESSAGE);            
        }else if(contraseña.equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar su contraseña", "Contraseña vacía", JOptionPane.ERROR_MESSAGE); 
        }else{
            acceso.setCurp(curpTxt.getText());
            acceso.setContraseña(contraseña);
            if(metodos.iniciarSesion(acceso)){
                VistaMenu menu = new VistaMenu();
                menu.setVisible(true);
                this.setVisible(false);         
            }else{
                JOptionPane.showMessageDialog(this, "Los datos ingresados son incorrectos.\nVuelva a verificar su contraseña y su usuario", "Datos incorrectos", JOptionPane.ERROR_MESSAGE);
            } 
        }                                      
    }//GEN-LAST:event_iniciarSesionBtnActionPerformed

    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirBtnActionPerformed

    private void registrarseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseBtnActionPerformed
        VistaRegistro registro = new VistaRegistro();
        registro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registrarseBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaIniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contraseñaLabel;
    private javax.swing.JPasswordField contraseñaTxt;
    private javax.swing.JTextField curpTxt;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel fondoEncabezado;
    private javax.swing.JPanel fondoTitulo;
    private javax.swing.JButton iniciarSesionBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton registrarseBtn;
    private javax.swing.JButton salirBtn;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel usuarioLabel;
    // End of variables declaration//GEN-END:variables
}
