package Vistas;

import Modelo.Acceso;
import Modelo.MetodosSQL;
import javax.swing.JOptionPane;

public class VistaRegistro extends javax.swing.JFrame {

    public VistaRegistro() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        fondoEncabezado = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fondoTitulo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        contraseñaLabel = new javax.swing.JLabel();
        usuarioLabel = new javax.swing.JLabel();
        registrarseBtn = new javax.swing.JButton();
        curpTxt = new javax.swing.JTextField();
        contraseñaTxt = new javax.swing.JPasswordField();
        regresarBtn = new javax.swing.JButton();
        contraseñaLabel2 = new javax.swing.JLabel();
        contraseña2Txt = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setPreferredSize(new java.awt.Dimension(1366, 768));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoEncabezado.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout fondoEncabezadoLayout = new javax.swing.GroupLayout(fondoEncabezado);
        fondoEncabezado.setLayout(fondoEncabezadoLayout);
        fondoEncabezadoLayout.setHorizontalGroup(
            fondoEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoEncabezadoLayout.setVerticalGroup(
            fondoEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fondo.add(fondoEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, -1));

        fondoTitulo.setBackground(new java.awt.Color(255, 51, 51));

        titulo.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("REGISTRARSE");

        javax.swing.GroupLayout fondoTituloLayout = new javax.swing.GroupLayout(fondoTitulo);
        fondoTitulo.setLayout(fondoTituloLayout);
        fondoTituloLayout.setHorizontalGroup(
            fondoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoTituloLayout.createSequentialGroup()
                .addContainerGap(630, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(580, 580, 580))
        );
        fondoTituloLayout.setVerticalGroup(
            fondoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo))
        );

        fondo.add(fondoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1440, -1));

        contraseñaLabel.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        contraseñaLabel.setText("CONTRASEÑA:");
        fondo.add(contraseñaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, -1, -1));

        usuarioLabel.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        usuarioLabel.setText("CURP:");
        fondo.add(usuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, -1, -1));

        registrarseBtn.setBackground(new java.awt.Color(255, 0, 0));
        registrarseBtn.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        registrarseBtn.setForeground(new java.awt.Color(255, 255, 255));
        registrarseBtn.setText("REGISTRARSE");
        registrarseBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        registrarseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseBtnActionPerformed(evt);
            }
        });
        fondo.add(registrarseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 730, 230, 48));

        curpTxt.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        fondo.add(curpTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 417, 54));

        contraseñaTxt.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        fondo.add(contraseñaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 420, 50));

        regresarBtn.setBackground(new java.awt.Color(255, 0, 0));
        regresarBtn.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        regresarBtn.setForeground(new java.awt.Color(255, 255, 255));
        regresarBtn.setText("REGRESAR");
        regresarBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });
        fondo.add(regresarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 740, -1, 48));

        contraseñaLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        contraseñaLabel2.setText("COMFIRMAR CONTRASEÑA:");
        fondo.add(contraseñaLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, -1, 60));

        contraseña2Txt.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        fondo.add(contraseña2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 570, 420, 50));
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));
        fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N
        fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inicia_sesion.png"))); // NOI18N
        fondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseBtnActionPerformed
        Acceso acceso = new Acceso();
        MetodosSQL metodos = new MetodosSQL();                                        
                
        char[] contraseñaArray = contraseñaTxt.getPassword();
        String contraseña = new String(contraseñaArray);
        
        char[] contraseña2Array = contraseña2Txt.getPassword();
        String contraseña2 = new String(contraseña2Array);             
        
        if(contraseña.equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar su contraseña", "Contraseña vacía", JOptionPane.ERROR_MESSAGE);     
        }else if(contraseña2.equals("")){
            JOptionPane.showMessageDialog(this, "Debe confirmar su contraseña", "Contraseña vacía", JOptionPane.ERROR_MESSAGE);     
        }else if(curpTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar su CURP", "CURP vacía", JOptionPane.ERROR_MESSAGE);     
        }else{
            acceso.setCurp(curpTxt.getText());
            if(contraseña.contains(contraseña2)){
                if(contraseña.length() >= 8){
                    acceso.setContraseña(contraseña);
                    if(metodos.registrarse(acceso)){
                        VistaIniciarSesion login = new VistaIniciarSesion();
                        login.setVisible(true);
                        this.setVisible(false);
                        JOptionPane.showMessageDialog(this, "El registro ha sido completado correctamente.\nInicie sesión", "Registro completado", JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        JOptionPane.showMessageDialog(this, "Hubo un error al registrarse\nVerifique sus datos nuevamente", "Registro no completado", JOptionPane.ERROR_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Las contraseña debe tener 8 dígitos como mínimo", "Error en contraseña", JOptionPane.ERROR_MESSAGE);
                }            
            }else{
                JOptionPane.showMessageDialog(this, "Las contraseñas deben ser iguales", "Error en contraseña", JOptionPane.ERROR_MESSAGE);
            }        
        }                            
    }//GEN-LAST:event_registrarseBtnActionPerformed

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        VistaIniciarSesion iniciarSesion = new VistaIniciarSesion();
        iniciarSesion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contraseña2Txt;
    private javax.swing.JLabel contraseñaLabel;
    private javax.swing.JLabel contraseñaLabel2;
    private javax.swing.JPasswordField contraseñaTxt;
    private javax.swing.JTextField curpTxt;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel fondoEncabezado;
    private javax.swing.JPanel fondoTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton registrarseBtn;
    private javax.swing.JButton regresarBtn;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel usuarioLabel;
    // End of variables declaration//GEN-END:variables
}
