package Vistas;

public class VistaMenu extends javax.swing.JFrame {

    public VistaMenu() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        fondo = new javax.swing.JPanel();
        fondoEncabezado = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        crearPedidoBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cerrarSesionBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        eliminarPedidoBtn2 = new javax.swing.JButton();
        fondoTitulo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        altaPersonalBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yram\\Downloads\\Diseño de aplicaciones\\SistemaCompras\\src\\Imagenes\\logo.png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setPreferredSize(new java.awt.Dimension(1366, 768));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoEncabezado.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout fondoEncabezadoLayout = new javax.swing.GroupLayout(fondoEncabezado);
        fondoEncabezado.setLayout(fondoEncabezadoLayout);
        fondoEncabezadoLayout.setHorizontalGroup(
            fondoEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoEncabezadoLayout.setVerticalGroup(
            fondoEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        fondo.add(fondoEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, -1));

        crearPedidoBtn.setBackground(new java.awt.Color(255, 0, 0));
        crearPedidoBtn.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        crearPedidoBtn.setForeground(new java.awt.Color(255, 255, 255));
        crearPedidoBtn.setText("CREAR PEDIDO");
        crearPedidoBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        crearPedidoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearPedidoBtnActionPerformed(evt);
            }
        });
        fondo.add(crearPedidoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, -1, 48));
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        cerrarSesionBtn.setBackground(new java.awt.Color(255, 0, 0));
        cerrarSesionBtn.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        cerrarSesionBtn.setForeground(new java.awt.Color(255, 255, 255));
        cerrarSesionBtn.setText("CERRAR SESIÓN");
        cerrarSesionBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cerrarSesionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionBtnActionPerformed(evt);
            }
        });
        fondo.add(cerrarSesionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 740, -1, 48));
        fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, -1, -1));

        eliminarPedidoBtn2.setBackground(new java.awt.Color(255, 0, 0));
        eliminarPedidoBtn2.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        eliminarPedidoBtn2.setForeground(new java.awt.Color(255, 255, 255));
        eliminarPedidoBtn2.setText("VER PEDIDOS");
        eliminarPedidoBtn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eliminarPedidoBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarPedidoBtn2ActionPerformed(evt);
            }
        });
        fondo.add(eliminarPedidoBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 550, -1, 48));

        fondoTitulo.setBackground(new java.awt.Color(255, 0, 0));

        titulo.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText(" MENÚ PRINCIPAL");

        javax.swing.GroupLayout fondoTituloLayout = new javax.swing.GroupLayout(fondoTitulo);
        fondoTitulo.setLayout(fondoTituloLayout);
        fondoTituloLayout.setHorizontalGroup(
            fondoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoTituloLayout.createSequentialGroup()
                .addContainerGap(503, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(639, 639, 639))
        );
        fondoTituloLayout.setVerticalGroup(
            fondoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        fondo.add(fondoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1440, -1));
        fondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 260, -1, -1));

        altaPersonalBtn.setBackground(new java.awt.Color(255, 0, 0));
        altaPersonalBtn.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        altaPersonalBtn.setForeground(new java.awt.Color(255, 255, 255));
        altaPersonalBtn.setText("ALTA PERSONAL");
        altaPersonalBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        altaPersonalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaPersonalBtnActionPerformed(evt);
            }
        });
        fondo.add(altaPersonalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 550, -1, 48));
        fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));
        fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, -1, -1));
        fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 280, -1, -1));
        fondo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inicia_sesion.png"))); // NOI18N
        fondo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 260, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        fondo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ver pedidos.png"))); // NOI18N
        fondo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N
        fondo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearPedidoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearPedidoBtnActionPerformed
        VistaPedido pedido = new VistaPedido();
        pedido.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_crearPedidoBtnActionPerformed

    private void cerrarSesionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionBtnActionPerformed
        VistaIniciarSesion login = new VistaIniciarSesion();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cerrarSesionBtnActionPerformed

    private void eliminarPedidoBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarPedidoBtn2ActionPerformed
        VistaPedidosRealizados vistaPedidos = new VistaPedidosRealizados();
        vistaPedidos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_eliminarPedidoBtn2ActionPerformed

    private void altaPersonalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaPersonalBtnActionPerformed
        VistaAltaPersonal altaPersonal = new VistaAltaPersonal();
        altaPersonal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_altaPersonalBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altaPersonalBtn;
    private javax.swing.JButton cerrarSesionBtn;
    private javax.swing.JButton crearPedidoBtn;
    private javax.swing.JButton eliminarPedidoBtn2;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel fondoEncabezado;
    private javax.swing.JPanel fondoTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
